export const EXERCISES = [
  // ── Chest ──
  { name: 'Bench Press (Barbell)',           category: 'Chest' },
  { name: 'Bench Press (Dumbbell)',          category: 'Chest' },
  { name: 'Bench Press (Smith Machine)',     category: 'Chest' },
  { name: 'Incline Bench Press (Barbell)',   category: 'Chest' },
  { name: 'Incline Bench Press (Dumbbell)',  category: 'Chest' },
  { name: 'Incline Bench Press (Smith Machine)', category: 'Chest' },
  { name: 'Decline Bench Press',             category: 'Chest' },
  { name: 'Decline Bench Press (Dumbbell)',  category: 'Chest' },
  { name: 'Incline Chest Press (Machine)',   category: 'Chest' },
  { name: 'Machine Chest Press',             category: 'Chest' },
  { name: 'Chest Fly (Dumbbell)',            category: 'Chest' },
  { name: 'Incline Chest Fly (Dumbbell)',    category: 'Chest' },
  { name: 'Chest Fly (Machine)',             category: 'Chest' },
  { name: 'Cable Fly',                       category: 'Chest' },
  { name: 'Low Cable Fly',                   category: 'Chest' },
  { name: 'High Cable Fly',                  category: 'Chest' },
  { name: 'Cable Crossover',                 category: 'Chest' },
  { name: 'Pec Deck',                        category: 'Chest' },
  { name: 'Push Up',                         category: 'Chest' },
  { name: 'Push Up (Weighted)',              category: 'Chest' },
  { name: 'Incline Push Up',                 category: 'Chest' },
  { name: 'Decline Push Up',                 category: 'Chest' },
  { name: 'Chest Dip',                       category: 'Chest' },
  { name: 'Landmine Press',                  category: 'Chest' },
  { name: 'Svend Press',                     category: 'Chest' },
  // ── Back ──
  { name: 'Deadlift (Barbell)',              category: 'Back' },
  { name: 'Deadlift (Dumbbell)',             category: 'Back' },
  { name: 'Deadlift (Trap Bar)',             category: 'Back' },
  { name: 'Romanian Deadlift',               category: 'Back' },
  { name: 'Sumo Deadlift',                   category: 'Back' },
  { name: 'Rack Pull',                       category: 'Back' },
  { name: 'Pull Up',                         category: 'Back' },
  { name: 'Pull Up (Weighted)',             category: 'Back' },
  { name: 'Chin Up',                         category: 'Back' },
  { name: 'Assisted Pull Up (Machine)',      category: 'Back' },
  { name: 'Lat Pulldown',                    category: 'Back' },
  { name: 'Lat Pulldown (Wide Grip)',        category: 'Back' },
  { name: 'Lat Pulldown (Close Grip)',       category: 'Back' },
  { name: 'Lat Pulldown (Neutral Grip)',     category: 'Back' },
  { name: 'Single Arm Lat Pulldown (Cable)', category: 'Back' },
  { name: 'Straight Arm Pulldown',           category: 'Back' },
  { name: 'Seated Cable Row',                category: 'Back' },
  { name: 'Cable Row (Wide Grip)',           category: 'Back' },
  { name: 'Bent Over Row (Barbell)',         category: 'Back' },
  { name: 'Bent Over Row (Dumbbell)',        category: 'Back' },
  { name: 'Pendlay Row',                     category: 'Back' },
  { name: 'T-Bar Row',                       category: 'Back' },
  { name: 'Chest Supported Row (Machine)',   category: 'Back' },
  { name: 'Chest Supported Row (Dumbbell)',  category: 'Back' },
  { name: 'Seated Row (Machine)',            category: 'Back' },
  { name: 'Single Arm Dumbbell Row',         category: 'Back' },
  { name: 'Meadows Row',                     category: 'Back' },
  { name: 'Inverted Row',                    category: 'Back' },
  { name: 'Face Pull',                       category: 'Back' },
  { name: 'Shrug (Barbell)',                 category: 'Back' },
  { name: 'Shrug (Dumbbell)',                category: 'Back' },
  { name: 'Shrug (Machine)',                 category: 'Back' },
  { name: 'Shrug (Cable)',                   category: 'Back' },
  // ── Shoulders ──
  { name: 'Overhead Press (Barbell)',        category: 'Shoulders' },
  { name: 'Overhead Press (Dumbbell)',       category: 'Shoulders' },
  { name: 'Overhead Press (Smith Machine)',  category: 'Shoulders' },
  { name: 'Seated Dumbbell Press',           category: 'Shoulders' },
  { name: 'Machine Shoulder Press',          category: 'Shoulders' },
  { name: 'Arnold Press',                    category: 'Shoulders' },
  { name: 'Push Press',                      category: 'Shoulders' },
  { name: 'Lateral Raise (Dumbbell)',        category: 'Shoulders' },
  { name: 'Lateral Raise (Cable)',           category: 'Shoulders' },
  { name: 'Lateral Raise (Machine)',         category: 'Shoulders' },
  { name: 'Lean-In Lateral Raise (Cable)',   category: 'Shoulders' },
  { name: 'Front Raise (Dumbbell)',          category: 'Shoulders' },
  { name: 'Front Raise (Cable)',             category: 'Shoulders' },
  { name: 'Front Raise (Plate)',             category: 'Shoulders' },
  { name: 'Rear Delt Fly (Dumbbell)',        category: 'Shoulders' },
  { name: 'Rear Delt Fly (Cable)',           category: 'Shoulders' },
  { name: 'Rear Delt Fly (Machine)',         category: 'Shoulders' },
  { name: 'Reverse Pec Deck',                category: 'Shoulders' },
  { name: 'Upright Row',                     category: 'Shoulders' },
  { name: 'Upright Row (Cable)',             category: 'Shoulders' },
  { name: 'Cuban Press',                     category: 'Shoulders' },
  { name: 'Landmine Shoulder Press',         category: 'Shoulders' },
  // ── Biceps ──
  { name: 'Barbell Curl',                    category: 'Biceps' },
  { name: 'EZ Bar Curl',                     category: 'Biceps' },
  { name: 'Dumbbell Curl',                   category: 'Biceps' },
  { name: 'Hammer Curl',                     category: 'Biceps' },
  { name: 'Hammer Curl (Cable)',             category: 'Biceps' },
  { name: 'Incline Dumbbell Curl',           category: 'Biceps' },
  { name: 'Cable Curl',                      category: 'Biceps' },
  { name: 'Bayesian Curl (Cable)',           category: 'Biceps' },
  { name: 'Preacher Curl',                   category: 'Biceps' },
  { name: 'Preacher Curl (Machine)',         category: 'Biceps' },
  { name: 'Preacher Curl (Dumbbell)',        category: 'Biceps' },
  { name: 'Concentration Curl',              category: 'Biceps' },
  { name: 'Spider Curl',                     category: 'Biceps' },
  { name: 'Reverse Curl',                    category: 'Biceps' },
  { name: 'Reverse Curl (Cable)',            category: 'Biceps' },
  { name: 'Bicep Curl (Machine)',            category: 'Biceps' },
  // ── Triceps ──
  { name: 'Tricep Pushdown (Cable)',         category: 'Triceps' },
  { name: 'Tricep Pushdown (Rope)',          category: 'Triceps' },
  { name: 'Tricep Pushdown (V-Bar)',         category: 'Triceps' },
  { name: 'Overhead Tricep Extension',       category: 'Triceps' },
  { name: 'Overhead Tricep Extension (Cable)', category: 'Triceps' },
  { name: 'Overhead Tricep Extension (Dumbbell)', category: 'Triceps' },
  { name: 'Skull Crusher',                   category: 'Triceps' },
  { name: 'Skull Crusher (EZ Bar)',          category: 'Triceps' },
  { name: 'Close Grip Bench Press',          category: 'Triceps' },
  { name: 'Tricep Dip',                      category: 'Triceps' },
  { name: 'Tricep Dip (Machine)',            category: 'Triceps' },
  { name: 'Bench Dip',                       category: 'Triceps' },
  { name: 'Diamond Push Up',                 category: 'Triceps' },
  { name: 'Tricep Kickback',                 category: 'Triceps' },
  { name: 'Tricep Kickback (Cable)',         category: 'Triceps' },
  { name: 'Tricep Extension (Machine)',      category: 'Triceps' },
  { name: 'JM Press',                        category: 'Triceps' },
  // ── Quads ──
  { name: 'Squat (Barbell)',                 category: 'Quads' },
  { name: 'Squat (Smith Machine)',           category: 'Quads' },
  { name: 'Front Squat',                     category: 'Quads' },
  { name: 'Goblet Squat',                    category: 'Quads' },
  { name: 'Hack Squat',                      category: 'Quads' },
  { name: 'Pendulum Squat',                  category: 'Quads' },
  { name: 'Leg Press',                       category: 'Quads' },
  { name: 'Leg Press (Single Leg)',          category: 'Quads' },
  { name: 'Leg Extension',                   category: 'Quads' },
  { name: 'Leg Extension (Single Leg)',      category: 'Quads' },
  { name: 'Bulgarian Split Squat',           category: 'Quads' },
  { name: 'Bulgarian Split Squat (Dumbbell)', category: 'Quads' },
  { name: 'Lunge (Barbell)',                 category: 'Quads' },
  { name: 'Lunge (Dumbbell)',                category: 'Quads' },
  { name: 'Walking Lunge',                   category: 'Quads' },
  { name: 'Sissy Squat',                     category: 'Quads' },
  { name: 'Box Squat',                       category: 'Quads' },
  // ── Hamstrings ──
  { name: 'Leg Curl (Lying)',                category: 'Hamstrings' },
  { name: 'Leg Curl (Seated)',               category: 'Hamstrings' },
  { name: 'Leg Curl (Standing)',             category: 'Hamstrings' },
  { name: 'Nordic Hamstring Curl',           category: 'Hamstrings' },
  { name: 'Romanian Deadlift (Dumbbell)',    category: 'Hamstrings' },
  { name: 'Romanian Deadlift (Smith Machine)', category: 'Hamstrings' },
  { name: 'Stiff Leg Deadlift',              category: 'Hamstrings' },
  { name: 'Good Morning',                    category: 'Hamstrings' },
  { name: 'Glute Ham Raise',                 category: 'Hamstrings' },
  { name: 'Cable Pull Through',              category: 'Hamstrings' },
  // ── Glutes ──
  { name: 'Hip Thrust (Barbell)',            category: 'Glutes' },
  { name: 'Hip Thrust (Machine)',            category: 'Glutes' },
  { name: 'Hip Thrust (Smith Machine)',      category: 'Glutes' },
  { name: 'Hip Thrust (Bodyweight)',         category: 'Glutes' },
  { name: 'Glute Bridge',                    category: 'Glutes' },
  { name: 'Cable Kickback',                  category: 'Glutes' },
  { name: 'Glute Kickback (Machine)',        category: 'Glutes' },
  { name: 'Sumo Squat',                      category: 'Glutes' },
  { name: 'Step Up',                         category: 'Glutes' },
  { name: 'Hip Abduction (Cable)',           category: 'Glutes' },
  { name: 'Abductor Machine',               category: 'Glutes' },
  { name: 'Hip Adduction (Machine)',         category: 'Glutes' },
  { name: 'Donkey Kick',                     category: 'Glutes' },
  // ── Calves ──
  { name: 'Calf Raise (Standing Machine)',   category: 'Calves' },
  { name: 'Calf Raise (Seated Machine)',     category: 'Calves' },
  { name: 'Calf Raise (Smith Machine)',      category: 'Calves' },
  { name: 'Calf Raise (Barbell)',            category: 'Calves' },
  { name: 'Calf Raise (Dumbbell)',           category: 'Calves' },
  { name: 'Calf Raise (Leg Press)',          category: 'Calves' },
  { name: 'Calf Press (Machine)',            category: 'Calves' },
  { name: 'Jump Rope',                       category: 'Calves' },
  // ── Core ──
  { name: 'Plank',                           category: 'Core' },
  { name: 'Side Plank',                      category: 'Core' },
  { name: 'Crunch',                          category: 'Core' },
  { name: 'Cable Crunch',                    category: 'Core' },
  { name: 'Crunch (Machine)',                category: 'Core' },
  { name: 'Leg Raise (Hanging)',             category: 'Core', logType: 'bodyweight' },
  { name: 'Leg Raise (Lying)',               category: 'Core' },
  { name: "Leg Raise (Captain's Chair)", category: 'Core' },
  { name: 'Russian Twist',                   category: 'Core' },
  { name: 'Ab Wheel Rollout',               category: 'Core' },
  { name: 'Decline Sit Up',                 category: 'Core' },
  { name: 'Sit Up',                          category: 'Core' },
  { name: 'Mountain Climber',                category: 'Core' },
  { name: 'Bicycle Crunch',                  category: 'Core' },
  { name: 'Dragon Flag',                     category: 'Core' },
  { name: 'Pallof Press',                    category: 'Core' },
  { name: 'Woodchopper (Cable)',             category: 'Core' },
  { name: 'Hollow Hold',                     category: 'Core' },
  // ── Cardio ──
  { name: 'Running (Treadmill)',             category: 'Cardio' },
  { name: 'Running (Outdoor)',               category: 'Cardio' },
  { name: 'Incline Walk (Treadmill)',        category: 'Cardio' },
  { name: 'Cycling (Stationary)',            category: 'Cardio' },
  { name: 'Cycling (Outdoor)',               category: 'Cardio' },
  { name: 'Rowing Machine',                  category: 'Cardio' },
  { name: 'Stair Master',                    category: 'Cardio' },
  { name: 'Assault Bike',                    category: 'Cardio' },
  { name: 'Ski Erg',                         category: 'Cardio' },
  { name: 'Elliptical',                      category: 'Cardio' },
  { name: 'Swimming',                        category: 'Cardio' },
];

export const CATEGORIES = [...new Set(EXERCISES.map(e => e.category))];

export const CATEGORY_COLORS = {
  Chest: '#f43f5e', Back: '#38bdf8', Shoulders: '#fbbf24',
  Biceps: '#34d399', Triceps: '#a78bfa', Quads: '#f97316',
  Hamstrings: '#f472b6', Glutes: '#e879f9', Calves: '#2dd4bf',
  Core: '#facc15', Cardio: '#60a5fa',
};
