export const EXERCISES = [
  // Chest
  { name: 'Bench Press (Barbell)',           category: 'Chest' },
  { name: 'Bench Press (Dumbbell)',          category: 'Chest' },
  { name: 'Incline Bench Press (Barbell)',   category: 'Chest' },
  { name: 'Incline Bench Press (Dumbbell)', category: 'Chest' },
  { name: 'Decline Bench Press',            category: 'Chest' },
  { name: 'Chest Fly (Dumbbell)',            category: 'Chest' },
  { name: 'Cable Fly',                       category: 'Chest' },
  { name: 'Push Up',                         category: 'Chest' },
  { name: 'Chest Dip',                       category: 'Chest' },
  { name: 'Machine Chest Press',             category: 'Chest' },
  { name: 'Pec Deck',                        category: 'Chest' },
  // Back
  { name: 'Deadlift (Barbell)',              category: 'Back' },
  { name: 'Romanian Deadlift',               category: 'Back' },
  { name: 'Sumo Deadlift',                   category: 'Back' },
  { name: 'Pull Up',                         category: 'Back' },
  { name: 'Chin Up',                         category: 'Back' },
  { name: 'Lat Pulldown',                    category: 'Back' },
  { name: 'Seated Cable Row',                category: 'Back' },
  { name: 'Bent Over Row (Barbell)',         category: 'Back' },
  { name: 'Bent Over Row (Dumbbell)',        category: 'Back' },
  { name: 'T-Bar Row',                       category: 'Back' },
  { name: 'Single Arm Dumbbell Row',         category: 'Back' },
  { name: 'Face Pull',                       category: 'Back' },
  { name: 'Rack Pull',                       category: 'Back' },
  { name: 'Cable Row (Wide Grip)',           category: 'Back' },
  { name: 'Straight Arm Pulldown',           category: 'Back' },
  // Shoulders
  { name: 'Overhead Press (Barbell)',        category: 'Shoulders' },
  { name: 'Overhead Press (Dumbbell)',       category: 'Shoulders' },
  { name: 'Lateral Raise (Dumbbell)',        category: 'Shoulders' },
  { name: 'Lateral Raise (Cable)',           category: 'Shoulders' },
  { name: 'Front Raise (Dumbbell)',          category: 'Shoulders' },
  { name: 'Arnold Press',                    category: 'Shoulders' },
  { name: 'Rear Delt Fly (Dumbbell)',        category: 'Shoulders' },
  { name: 'Rear Delt Fly (Cable)',           category: 'Shoulders' },
  { name: 'Upright Row',                     category: 'Shoulders' },
  { name: 'Machine Shoulder Press',          category: 'Shoulders' },
  { name: 'Cuban Press',                     category: 'Shoulders' },
  // Biceps
  { name: 'Barbell Curl',                    category: 'Biceps' },
  { name: 'Dumbbell Curl',                   category: 'Biceps' },
  { name: 'Hammer Curl',                     category: 'Biceps' },
  { name: 'Incline Dumbbell Curl',           category: 'Biceps' },
  { name: 'Cable Curl',                      category: 'Biceps' },
  { name: 'Preacher Curl',                   category: 'Biceps' },
  { name: 'Concentration Curl',              category: 'Biceps' },
  { name: 'Spider Curl',                     category: 'Biceps' },
  { name: 'Reverse Curl',                    category: 'Biceps' },
  // Triceps
  { name: 'Tricep Pushdown (Cable)',         category: 'Triceps' },
  { name: 'Skull Crusher',                   category: 'Triceps' },
  { name: 'Overhead Tricep Extension',       category: 'Triceps' },
  { name: 'Close Grip Bench Press',          category: 'Triceps' },
  { name: 'Tricep Dip',                      category: 'Triceps' },
  { name: 'Diamond Push Up',                 category: 'Triceps' },
  { name: 'Tricep Kickback',                 category: 'Triceps' },
  // Quads
  { name: 'Squat (Barbell)',                 category: 'Quads' },
  { name: 'Front Squat',                     category: 'Quads' },
  { name: 'Leg Press',                       category: 'Quads' },
  { name: 'Hack Squat',                      category: 'Quads' },
  { name: 'Leg Extension',                   category: 'Quads' },
  { name: 'Bulgarian Split Squat',           category: 'Quads' },
  { name: 'Lunge (Barbell)',                 category: 'Quads' },
  { name: 'Lunge (Dumbbell)',                category: 'Quads' },
  { name: 'Goblet Squat',                    category: 'Quads' },
  { name: 'Sissy Squat',                     category: 'Quads' },
  // Hamstrings
  { name: 'Leg Curl (Lying)',                category: 'Hamstrings' },
  { name: 'Leg Curl (Seated)',               category: 'Hamstrings' },
  { name: 'Nordic Hamstring Curl',           category: 'Hamstrings' },
  { name: 'Romanian Deadlift (Dumbbell)',    category: 'Hamstrings' },
  { name: 'Good Morning',                    category: 'Hamstrings' },
  { name: 'Glute Ham Raise',                 category: 'Hamstrings' },
  // Glutes
  { name: 'Hip Thrust (Barbell)',            category: 'Glutes' },
  { name: 'Hip Thrust (Bodyweight)',         category: 'Glutes' },
  { name: 'Cable Kickback',                  category: 'Glutes' },
  { name: 'Sumo Squat',                      category: 'Glutes' },
  { name: 'Step Up',                         category: 'Glutes' },
  { name: 'Abductor Machine',               category: 'Glutes' },
  { name: 'Donkey Kick',                     category: 'Glutes' },
  // Calves
  { name: 'Calf Raise (Standing Machine)',   category: 'Calves' },
  { name: 'Calf Raise (Seated Machine)',     category: 'Calves' },
  { name: 'Calf Raise (Barbell)',            category: 'Calves' },
  { name: 'Calf Raise (Leg Press)',          category: 'Calves' },
  { name: 'Jump Rope',                       category: 'Calves' },
  // Core
  { name: 'Plank',                           category: 'Core' },
  { name: 'Side Plank',                      category: 'Core' },
  { name: 'Crunch',                          category: 'Core' },
  { name: 'Cable Crunch',                    category: 'Core' },
  { name: 'Leg Raise (Hanging)',             category: 'Core' },
  { name: 'Leg Raise (Lying)',               category: 'Core' },
  { name: 'Russian Twist',                   category: 'Core' },
  { name: 'Ab Wheel Rollout',               category: 'Core' },
  { name: 'Decline Sit Up',                 category: 'Core' },
  { name: 'Dragon Flag',                     category: 'Core' },
  { name: 'Pallof Press',                    category: 'Core' },
  // Cardio
  { name: 'Running (Treadmill)',             category: 'Cardio' },
  { name: 'Cycling (Stationary)',            category: 'Cardio' },
  { name: 'Rowing Machine',                  category: 'Cardio' },
  { name: 'Stair Master',                    category: 'Cardio' },
  { name: 'Assault Bike',                    category: 'Cardio' },
  { name: 'Ski Erg',                         category: 'Cardio' },
  { name: 'Elliptical',                      category: 'Cardio' },
];

export const CATEGORIES = [...new Set(EXERCISES.map(e => e.category))];

export const CATEGORY_COLORS = {
  Chest: '#e94560', Back: '#4fc3f7', Shoulders: '#fbbf24',
  Biceps: '#34d399', Triceps: '#a78bfa', Quads: '#f97316',
  Hamstrings: '#f472b6', Glutes: '#e879f9', Calves: '#2dd4bf',
  Core: '#facc15', Cardio: '#60a5fa',
};
